#include "touchstone/TouchstoneWriter.h"

#include <cstddef>
#include <format>
#include <fstream>
#include <sstream>

namespace sikit::touchstone {

std::string TouchstoneWriter::to_string(const TouchstoneFile& f) {
    if (f.num_ports < 1) {
        throw TouchstoneParseError("write: num_ports must be >= 1");
    }
    if (f.frequencies.size() != f.s_matrices.size()) {
        throw TouchstoneParseError(std::format(
            "write: frequencies ({}) and s_matrices ({}) length mismatch",
            f.frequencies.size(), f.s_matrices.size()));
    }
    const std::size_t expected = static_cast<std::size_t>(f.num_ports) *
                                  static_cast<std::size_t>(f.num_ports);
    for (std::size_t k = 0; k < f.s_matrices.size(); ++k) {
        if (f.s_matrices[k].size() != expected) {
            throw TouchstoneParseError(std::format(
                "write: s_matrices[{}] has {} entries, expected {}",
                k, f.s_matrices[k].size(), expected));
        }
    }

    std::ostringstream os;
    os << "! Generated by sikit\n";
    os << "! ports=" << f.num_ports << "  Zref=" << f.reference_impedance << " Ohm\n";
    // Always emit in RI form with Hz units — universally accepted.
    os << "# Hz S RI R " << f.reference_impedance << "\n";

    const int N = f.num_ports;
    for (std::size_t k = 0; k < f.frequencies.size(); ++k) {
        os << std::format("{:.9e}", f.frequencies[k]);

        if (N == 2) {
            // Historical Touchstone 2-port order: S11 S21 S12 S22.
            // Storage is column-major: [S11, S21, S12, S22] at indices 0..3.
            for (std::size_t i = 0; i < 4; ++i) {
                const auto& z = f.s_matrices[k][i];
                os << std::format("  {:.9e} {:.9e}", z.real(), z.imag());
            }
        } else {
            // N != 2: row-major in the file. Storage is column-major
            // ([r + c*N]), so we re-iterate by file order (r outer, c inner).
            for (int r = 0; r < N; ++r) {
                for (int c = 0; c < N; ++c) {
                    const auto& z = f.s_matrices[k][r + c * N];
                    os << std::format("  {:.9e} {:.9e}", z.real(), z.imag());
                }
                if (r + 1 < N) os << "\n  ";  // line-wrap rows
            }
        }
        os << "\n";
    }
    return os.str();
}

void TouchstoneWriter::write_file(const TouchstoneFile& f,
                                   const std::filesystem::path& path) {
    std::ofstream out(path);
    if (!out) {
        throw TouchstoneParseError(std::format(
            "write: cannot open file: {}", path.string()));
    }
    out << to_string(f);
}

}  // namespace sikit::touchstone
